//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "application_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub application: i64,
    #[sea_orm(unique)]
    pub hash: String,
    pub name: String,
    pub created_at: i64,
    pub updated_at: i64,
    pub deleted_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::application_global_settings::Entity")]
    ApplicationGlobalSettings,
    #[sea_orm(has_many = "super::application_user_settings::Entity")]
    ApplicationUserSettings,
    #[sea_orm(
        belongs_to = "super::applications::Entity",
        from = "Column::Application",
        to = "super::applications::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Applications,
}

impl Related<super::application_global_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationGlobalSettings.def()
    }
}

impl Related<super::application_user_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApplicationUserSettings.def()
    }
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
