//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::application_global_settings::Entity as ApplicationGlobalSettings;
pub use super::application_process_logs::Entity as ApplicationProcessLogs;
pub use super::application_processes::Entity as ApplicationProcesses;
pub use super::application_settings::Entity as ApplicationSettings;
pub use super::application_user_settings::Entity as ApplicationUserSettings;
pub use super::applications::Entity as Applications;
